[2025-02-17T19:59:08.602+0000] {processor.py:157} INFO - Started process (PID=233) to work on /opt/airflow/dags/py.py
[2025-02-17T19:59:08.602+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/py.py for tasks to queue
[2025-02-17T19:59:08.602+0000] {logging_mixin.py:151} INFO - [2025-02-17T19:59:08.602+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/py.py
[2025-02-17T19:59:08.944+0000] {logging_mixin.py:151} INFO - [2025-02-17T19:59:08.943+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/py.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/py.py", line 7, in <module>
    import librosa
ModuleNotFoundError: No module named 'librosa'
[2025-02-17T19:59:08.944+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/py.py
[2025-02-17T19:59:08.954+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/py.py took 0.355 seconds
[2025-02-17T19:59:39.071+0000] {processor.py:157} INFO - Started process (PID=246) to work on /opt/airflow/dags/py.py
[2025-02-17T19:59:39.072+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/py.py for tasks to queue
[2025-02-17T19:59:39.072+0000] {logging_mixin.py:151} INFO - [2025-02-17T19:59:39.072+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/py.py
[2025-02-17T19:59:39.398+0000] {logging_mixin.py:151} INFO - [2025-02-17T19:59:39.397+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/py.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/py.py", line 7, in <module>
    import librosa
ModuleNotFoundError: No module named 'librosa'
[2025-02-17T19:59:39.398+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/py.py
[2025-02-17T19:59:39.411+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/py.py took 0.342 seconds
[2025-02-17T20:00:09.529+0000] {processor.py:157} INFO - Started process (PID=252) to work on /opt/airflow/dags/py.py
[2025-02-17T20:00:09.531+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/py.py for tasks to queue
[2025-02-17T20:00:09.531+0000] {logging_mixin.py:151} INFO - [2025-02-17T20:00:09.531+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/py.py
[2025-02-17T20:00:09.875+0000] {logging_mixin.py:151} INFO - [2025-02-17T20:00:09.874+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/py.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/py.py", line 7, in <module>
    import librosa
ModuleNotFoundError: No module named 'librosa'
[2025-02-17T20:00:09.876+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/py.py
[2025-02-17T20:00:09.892+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/py.py took 0.365 seconds
[2025-02-17T20:00:40.016+0000] {processor.py:157} INFO - Started process (PID=258) to work on /opt/airflow/dags/py.py
[2025-02-17T20:00:40.017+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/py.py for tasks to queue
[2025-02-17T20:00:40.018+0000] {logging_mixin.py:151} INFO - [2025-02-17T20:00:40.018+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/py.py
[2025-02-17T20:00:40.344+0000] {logging_mixin.py:151} INFO - [2025-02-17T20:00:40.343+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/py.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/py.py", line 7, in <module>
    import librosa
ModuleNotFoundError: No module named 'librosa'
[2025-02-17T20:00:40.344+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/py.py
[2025-02-17T20:00:40.355+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/py.py took 0.342 seconds
